### docker-compose.yml
version: '3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    

  spring_app:
    container_name: tp
    image: tp
    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - mysqldb